import {useEffect,useMemo,useRef,useState} from 'react';
import PlantScene from './PlantScene';
import {downloadPlantGLB} from './exportPlantModel';
import {getWorkflowState,SCENARIOS} from './workflow';
import RegionMap from './RegionMap';
import ProcessFlow from './ProcessFlow';
import SceneObjectCard from './SceneObjectCard';
import {getOperations,entityDetail} from './operations';
import './styles-v4.css';
import './styles-v5.css';
import './styles-v5-shell.css';
import './styles-v5-wide.css';
import './styles-v5-compact.css';
import './styles-v6-interaction.css';

const fmt=n=>Number(n||0).toFixed(1);
const clock=n=>Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0');
const number=n=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:1});
const NAV={production:'生产',materials:'原料',delivery:'配送',alerts:'异常'};
const QUALITY_LABELS={auto:'自动',high:'精细',balanced:'均衡',low:'流畅'};
const VIEWS={overview:'站区总览',materials:'原料作业',control:'中控操作',detail:'主楼剖视',delivery:'装车发运',vehicle:'车辆近景',supplier:'厂家装车',site:'工地泵送',wash:'返站洗车',regional:'区域模型'};
const DELIVERY_GROUPS=[['配方',0,2,0],['生产',3,3,3],['装车',4,5,4],['运输',6,6,6],['泵送',7,8,8],['签收',9,9,9],['返站',10,12,10]];
const RAW_GROUPS=[['厂家',0,0,0],['运输',1,1,1],['验收',2,4,4],['卸料',5,6,6],['入库',7,9,8],['供料',10,11,11],['完成',12,12,12]];

function Icon({name,size=18}){
  const paths={plant:<><path d="M3 21V9l6 4V9l6 4V4h5v17H3Z"/><path d="M7 17h1m4 0h1m5-9h1"/></>,truck:<><path d="M2 5h12v12H2zM14 10h4l4 5v2h-8"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>,layers:<><path d="m12 3 10 5-10 5L2 8l10-5Zm-10 9 10 5 10-5M2 16l10 5 10-5"/></>,alert:<><path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3v.1"/></>,focus:<><path d="M8 3H3v5m13-5h5v5M3 16v5h5m8 0h5v-5"/><circle cx="12" cy="12" r="3"/></>,play:<path d="m8 4 12 8-12 8V4Z"/>,pause:<><path d="M8 5v14M16 5v14"/></>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,check:<path d="m5 12 4 4 10-10"/>,reset:<><path d="M4 9a8 8 0 1 1 0 6M4 3v6h6"/></>,gear:<><circle cx="12" cy="12" r="4"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/></>};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.plant}</svg>;
}
export default function App(){
  const [workspace,setWorkspace]=useState('production'),[scenarioId,setScenarioId]=useState('delivery'),[time,setTime]=useState(0),[paused,setPaused]=useState(true),[speed,setSpeed]=useState(1);
  const [selectedId,setSelectedId]=useState('control-room'),[view,setView]=useState('overview'),[autoCamera,setAutoCamera]=useState(true),[cutaway,setCutaway]=useState(false),[surface,setSurface]=useState('3d');
  const [showRoutes,setShowRoutes]=useState(true),[faultActive,setFaultActive]=useState(false),[acknowledged,setAcknowledged]=useState(false),[ready,setReady]=useState(false),[fullscreen,setFullscreen]=useState(false);
  const [focusId,setFocusId]=useState(null),[focusRequest,setFocusRequest]=useState(0),[detailsOpen,setDetailsOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[sourceOpen,setSourceOpen]=useState(false);
  const [exporting,setExporting]=useState(false),[message,setMessage]=useState(''),[modelFile,setModelFile]=useState(null);
  const [replenishment,setReplenishment]=useState(null),[replenishmentQty,setReplenishmentQty]=useState(30);
  const sceneRef=useRef(null),messageTimer=useRef(null);
  const visualClock=useRef({time:0,paused:true,speed:1,scenarioId:'delivery'}),liveSettings=useRef(null);
  const [locationId,setLocationId]=useState(null),[thumbnails,setThumbnails]=useState({}),[sampling,setSampling]=useState(false),[renderStats,setRenderStats]=useState(null);
  const [objectCardOpen,setObjectCardOpen]=useState(false),[quality,setQuality]=useState('auto'),[qualityState,setQualityState]=useState(null);
  const [followRequest,setFollowRequest]=useState(0);
  const updateTime=value=>{visualClock.current.time=Number(value);visualClock.current.pendingBoundary=null;setTime(Number(value));};
  const state=useMemo(()=>getWorkflowState(scenarioId,time),[scenarioId,time]),isDelivery=state.flowKind==='concrete';
  const operations=useMemo(()=>{const value=getOperations(state,{faultActive,acknowledged});if(replenishment)value.alerts=value.alerts.map(alert=>alert.id==='snapshot-low-c02'?{...alert,status:'已安排 · 待收货',description:replenishment.task+' · 补料 '+replenishment.quantity+' t，尚未到货复磅，库存保持原值。'}:alert);return value;},[state,faultActive,acknowledged,replenishment]);
  const detail=useMemo(()=>{
    if(!selectedId.startsWith('location-'))return entityDetail(selectedId,state,{faultActive,acknowledged});
    const id=selectedId.slice(9),raw=state.flowKind!=='concrete';
    const locations={supplier:{type:'厂家作业',title:raw?state.short+'供应厂家':'原料供应端',status:state.stageName==='supplier_loading'?'装车作业':'发运与运输',fields:[['当前任务',state.task],['运输车辆',state.vehicleCode],['发运物料',raw?state.short:'砂石 / 粉料'],['作业环节',state.phase.label]],nextAction:{type:'focus',targetId:'supplier-yard',label:'查看厂家装料'}},plant:{type:'站区运营',title:'一号搅拌站',status:state.phase.label,fields:[['当前车辆',state.vehicleCode],['收货状态',raw?(state.receipted?'已复磅入库':'待复磅确认'):'成品配送'],['生产环节',state.productionStep||'原料作业'],['本趟任务',state.task]],nextAction:{type:'focus',targetId:raw?'weighbridge-w01':'control-room',label:raw?'查看称重入库':'进入中控操作'}},site:{type:'工地交付',title:'南城建设工地',status:state.delivered?'已签收':['queue','unloading','signature'].includes(state.stageName)?state.phase.label:'等待配送',fields:[['配送车辆',state.flowKind==='concrete'?state.vehicleCode:'MC012'],['当前交付',fmt(state.deliveredVolume)+' m³'],['泵送设备','P01'],['当前任务',state.task]],nextAction:{type:'focus',targetId:'pump-p01',label:'查看泵送作业'}}};
    if(id==='supplier'&&!raw){locations.supplier.fields=[['供应物料','砂石 / 水泥 / 粉煤灰'],['供应去向','一号搅拌站'],['作业流程','查看原料任务'],['当前浏览','厂家模型']];locations.supplier.nextAction={type:'raw_tasks',label:'查看原料任务'};}
    if(id==='site'&&raw){locations.site.fields=[['施工项目','南城建设工地'],['泵送设备','P01'],['配送流程','查看混凝土配送'],['当前浏览','工地模型']];locations.site.nextAction={type:'delivery_tasks',label:'查看混凝土配送'};}
    return {...locations[id],source:'workflow'};
  },[selectedId,state,faultActive,acknowledged]);
  const blocked=operations.summary.blocked;
  const groups=isDelivery?DELIVERY_GROUPS:RAW_GROUPS;
  const notify=text=>{clearTimeout(messageTimer.current);setMessage(text);messageTimer.current=setTimeout(()=>setMessage(''),4500);};
  useEffect(()=>()=>clearTimeout(messageTimer.current),[]);
  useEffect(()=>{if(!autoCamera)return;const key=state.stageName;if(isDelivery){const initial=state.time===0&&paused;setView(initial?'overview':['mix_design','trial','approval'].includes(key)?'control':['production','loading'].includes(key)?'detail':key==='release'?'delivery':['outbound','return'].includes(key)?'vehicle':['queue','unloading','signature'].includes(key)?'site':['wash','complete'].includes(key)?'wash':'overview');setCutaway(!initial&&['mix_design','trial','approval','production','loading'].includes(key));setSurface(['outbound','return'].includes(key)?'map':'3d');}else{setView(key==='supplier_loading'?'supplier':key==='arrival'?'vehicle':'materials');setCutaway(false);setSurface(['arrival','exit'].includes(key)?'map':'3d');}},[autoCamera,scenarioId,state.stageName,isDelivery,paused]);
  liveSettings.current={paused:paused||blocked||state.completed,speed,total:state.total,stageEnd:state.phase.start+state.phase.duration};
  visualClock.current.paused=liveSettings.current.paused;visualClock.current.speed=speed;visualClock.current.scenarioId=scenarioId;
  useEffect(()=>{let frame,last=performance.now(),lastUI=last;
    const tick=now=>{const config=liveSettings.current,delta=Math.min((now-last)/1000,.12);last=now;
      if(config&&!config.paused){if(visualClock.current.pendingBoundary!=null&&config.stageEnd>visualClock.current.pendingBoundary)visualClock.current.pendingBoundary=null;
        const previous=visualClock.current.time,candidate=visualClock.current.pendingBoundary==null?Math.min(config.total,previous+delta*config.speed):previous;
        visualClock.current.time=previous<config.stageEnd&&candidate>=config.stageEnd?config.stageEnd:candidate;
        if(previous<config.stageEnd&&candidate>=config.stageEnd)visualClock.current.pendingBoundary=config.stageEnd;
        if(now-lastUI>=250||previous<config.stageEnd&&visualClock.current.time>=config.stageEnd||visualClock.current.time>=config.total){lastUI=now;setTime(visualClock.current.time);}
        if(visualClock.current.time>=config.total)setPaused(true);
      }frame=requestAnimationFrame(tick);};
    frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
  },[]);
  useEffect(()=>{const handler=e=>{if(e.key==='Escape'){setObjectCardOpen(false);setFullscreen(false);setSettingsOpen(false);setSourceOpen(false);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
  const chooseScenario=id=>{setScenarioId(id);updateTime(0);setLocationId(null);setPaused(true);setAutoCamera(true);setObjectCardOpen(false);setSelectedId(id==='delivery'?'control-room':SCENARIOS[id].targetId);setFaultActive(false);setAcknowledged(false);setFocusId(null);};
  const chooseWorkspace=id=>{setObjectCardOpen(false);setWorkspace(id);if(id==='materials'){if(isDelivery)chooseScenario('sand');setSurface('3d');}if(['production','delivery'].includes(id)){if(!isDelivery)chooseScenario('delivery');setSelectedId(id==='production'?'control-room':'truck-mc012');setAutoCamera(false);setSurface(id==='delivery'?'map':'3d');setView('overview');setCutaway(false);setFocusId(null);}if(id==='alerts'){setSelectedId(faultActive?'conveyor-b01':'cement-c02');setSurface('3d');setAutoCamera(false);setView('overview');setFocusId(null);}};
  const seek=value=>{updateTime(Math.max(0,Math.min(state.total,Number(value))));setPaused(true);};
  const jumpStage=(stage,play=false)=>{const checkpoint=play?0:['gross','tare','signature','wash','trial','approval'].includes(stage.key)?.8:stage.key==='supply'?.5:stage.key==='loading'&&!isDelivery?.65:.5;seek(stage.start+stage.duration*checkpoint);if(play)setPaused(false);setAutoCamera(true);setFocusId(null);setSelectedId(['mix_design','trial','approval'].includes(stage.key)?'control-room':!isDelivery&&['loading','supply'].includes(stage.key)?state.flowKind==='aggregate'?'loader-l01':state.targetId:state.vehicleId);};
  const restart=()=>{updateTime(0);setLocationId(null);setObjectCardOpen(false);setPaused(false);setAutoCamera(true);setFocusId(null);};
  const togglePlay=()=>{if(blocked){setWorkspace('alerts');setSelectedId('conveyor-b01');return;}if(state.completed){restart();return;}setPaused(!paused);};
  const chooseView=id=>{setLocationId(['supplier','site'].includes(id)?id:'plant');setView(id);setAutoCamera(false);setSurface('3d');setFocusId(null);setCutaway(['detail','control'].includes(id));if(id==='vehicle'||id==='wash')setSelectedId(state.vehicleId);if(id==='control')setSelectedId('control-room');};
  const enterLocation=id=>{setLocationId(id);setSelectedId('location-'+id);setObjectCardOpen(false);setAutoCamera(false);setSurface('3d');setCutaway(false);setFocusId(null);setView(id==='supplier'?'supplier':id==='site'?'site':'overview');};
  const returnToMap=()=>{setSurface('map');setObjectCardOpen(false);setAutoCamera(false);setFocusId(null);};
  const selectObject=id=>{setSelectedId(id);setObjectCardOpen(true);};
  const manualControl=()=>{setAutoCamera(false);setFocusId(null);};
  const resumeFollow=()=>{setFocusId(null);setAutoCamera(true);setFollowRequest(value=>value+1);};
  const focusObject=id=>{if(id.startsWith('location-')){enterLocation(id.slice(9));setObjectCardOpen(true);return;}setObjectCardOpen(true);setLocationId(id==='construction-site'||id==='pump-p01'?'site':id==='supplier-yard'?'supplier':'plant');if(id.startsWith('snapshot-')){setSelectedId(id);return;}setSelectedId(id);setAutoCamera(false);setSurface('3d');const washVehicle=isDelivery&&id===state.vehicleId&&['wash','complete'].includes(state.stageName);const productionObject=['mixer-m01','aggregate-scale-m01','powder-scale-m01','water-scale-m01','mixer-discharge-m01'].includes(id);setCutaway(productionObject||id==='control-room'||/^(cement|flyash)-/.test(id));setView(washVehicle?'wash':productionObject?'detail':id==='control-room'?'control':id==='construction-site'||id==='pump-p01'?'site':id==='supplier-yard'?'supplier':/^(cement|flyash)-/.test(id)?'materials':id===state.vehicleId?'vehicle':'overview');setFocusId(washVehicle?null:id);if(washVehicle)setFollowRequest(n=>n+1);else setFocusRequest(n=>n+1);};
  const controlAction=action=>{if(!isDelivery)return;const key=action==='trial'?'trial':action==='approve'?'approval':'production';if(key==='approval'&&!state.trialPassed)return;if(key==='production'&&!state.recipeApproved)return;if(faultActive&&key==='production'){notify('B01 故障待处理，清除后可启动生产。');setWorkspace('alerts');return;}const stage=state.stages.find(s=>s.key===key);updateTime(stage.start+stage.duration*(key==='production'?0:.82));setPaused(key!=='production');setSelectedId('control-room');setAutoCamera(true);setFocusId(null);};
  const handleAction=action=>{if(!action)return;if(action.type==='raw_tasks'){chooseWorkspace('materials');}else if(action.type==='delivery_tasks'){chooseWorkspace('delivery');}else if(action.type==='clear_fault'){setFaultActive(false);setAcknowledged(false);notify('已清除演示故障，点击继续恢复流程。');}else if(action.type==='acknowledge'){setAcknowledged(true);setSelectedId('conveyor-b01');notify('异常已确认，故障仍待处理。');}else if(action.type==='snapshot'){setSelectedId(action.targetId);notify('这是示例快照任务，暂未接入调度系统。');}else focusObject(action.targetId);};
  const exportModel=async()=>{if(!sceneRef.current||exporting)return;setExporting(true);try{const file=await downloadPlantGLB(sceneRef.current);setModelFile(file);notify('模型已生成，可点击下载 GLB 保存。');}catch(error){notify('导出失败：'+error.message);}finally{setExporting(false);}};
  const current=operations.fleet[0],production=operations.kpis[0],delivery=operations.kpis[1];
  const mainAction=blocked?'处理异常':state.completed?'重新演示':paused?'继续演示':'暂停演示';
  const recipeVisible=isDelivery&&['control-room','mixer-m01'].includes(selectedId);
  const detailFields=detail.fields.filter(([key])=>!['数据来源','结果来源','计量来源','签收来源','试配结果'].includes(key)).slice(0,workspace==='materials'&&detail.type==='原料库存'?2:4);
  const planReplenishment=()=>{const quantity=Number(replenishmentQty);if(!Number.isFinite(quantity)||quantity<1||quantity>50){notify('补料数量须为 1–50 t。');return;}setReplenishment({task:'DEMO-REPL-C02',quantity,warehouse:'C02 水泥筒仓'});notify('已创建 C02 演示补料单，库存将在收货复磅后更新。');};
  return <div className="ops-shell">
    <header className="ops-header"><div className="ops-brand"><span>砼</span><div><strong>砼联 · 运营中心</strong><small>一号搅拌站</small></div></div><nav aria-label="运营业务">{Object.entries(NAV).map(([id,label])=><button key={id} className={workspace===id?'active':''} aria-pressed={workspace===id} onClick={()=>chooseWorkspace(id)}><Icon name={id==='production'?'plant':id==='materials'?'layers':id==='delivery'?'truck':'alert'}/>{label}{id==='alerts'&&<b>{operations.alerts.length}</b>}</button>)}</nav><div className="header-right"><button className="demo-badge" aria-expanded={sourceOpen} onClick={()=>setSourceOpen(!sourceOpen)}><i/>演示模式</button><button className="icon-button" aria-label="演示与导出设置" aria-expanded={settingsOpen} onClick={()=>setSettingsOpen(!settingsOpen)}><Icon name="gear"/></button></div></header>
    {sourceOpen&&<div className="source-note" role="status">当前任务随流程动态变化；全站基准、另外两辆车和 C02 补料提醒为示例快照。尚未连接 PLC、地磅、GPS 或料位传感器；试配按钮用于流程预演。</div>}
    <section className="kpi-strip" aria-label="全站概况"><div className="kpi-production"><span>今日生产</span><strong>{number(production.value)}<em>m³</em></strong><small>计划 {number(production.plan)}</small><div className="metric-track"><i style={{width:production.ratio*100+'%'}}/></div></div><div><span>今日签收</span><strong>{number(delivery.value)}<em>m³</em></strong><small>本趟 + {fmt(state.deliveredVolume)} m³</small></div><div><span>主机状态</span><strong className={'status-value '+(blocked?'red':'')}>{blocked?'供料阻断':isDelivery&&['production','loading'].includes(state.stageName)?'生产中':'待机 / 准备'}</strong><small>M01 · {isDelivery?state.productionStep:'原料作业'}</small></div><button className="kpi-link" onClick={()=>chooseWorkspace('delivery')}><span>车辆任务</span><strong>3<em>辆</em></strong><small title="1 辆流程联动 · 2 辆示例快照">1 联动 · 2 示例快照</small></button><button className="kpi-link" onClick={()=>chooseWorkspace('alerts')}><span>异常与待办</span><strong className={faultActive?'red':'amber'}>{operations.alerts.length}<em>项</em></strong><small>{faultActive?'B01 异常待处理':'C02 示例补料提醒'}</small></button></section>
    <main className={'ops-workspace '+(fullscreen?'expanded':'')}>
      <section className="scene-panel" aria-label="生产与物流场景">
        <div className="scene-toolbar"><div className="scene-title"><span className={'status-dot '+(blocked?'red':paused?'gray':'')}/><strong>{surface==='map'?'站外运输路线':VIEWS[view]}</strong><small>{blocked?'流程阻断':state.completed?'本趟完成':paused?'已暂停':'运行中'}</small></div><div className="scene-actions"><div className="surface-switch"><button className={surface==='3d'?'active':''} onClick={()=>{setSurface('3d');setAutoCamera(false);}}>3D</button><button className={surface==='map'?'active':''} onClick={()=>{setSurface('map');setAutoCamera(false);}}>路线</button></div><select aria-label="查看场景" value={view} onChange={e=>chooseView(e.target.value)}>{Object.entries(VIEWS).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select><button className="icon-button" aria-label={fullscreen?'退出全屏':'全屏场景'} onClick={()=>setFullscreen(!fullscreen)}><Icon name="focus"/></button></div></div>
        <div className="scene-viewport"><div className={'three-surface '+(surface==='map'?'hidden-surface':'')}><PlantScene visible={surface==='3d'} visualClock={visualClock} sampling={sampling} onPerformance={setRenderStats} onThumbnails={setThumbnails} selectedId={selectedId} onSelect={selectObject} onManualControl={manualControl} followRequest={followRequest} quality={quality} onQualityChange={setQualityState} paused={paused||blocked||state.completed} view={view} focusId={focusId} focusRequest={focusRequest} showRoutes={showRoutes} faultActive={faultActive} cutaway={cutaway} workflow={state} onControlAction={controlAction} onReady={()=>setReady(true)} onSceneReady={scene=>{sceneRef.current=scene;setReady(true);}}/></div>{surface==='map'&&<RegionMap workflow={state} onEnter={enterLocation} selectedLocationId={locationId} thumbnails={thumbnails} visualClock={visualClock} showRoutes={showRoutes}/>}
          <div className="v5-location-path"><button onClick={returnToMap}>运输总览</button>{surface==='3d'&&locationId&&<><span>›</span><strong>{{supplier:'原料厂家',plant:'一号搅拌站',site:'南城工地'}[locationId]}</strong></>}</div>
          <div className="scene-context"><span>{isDelivery?'成品配送':'原料收货'}</span><strong>{state.vehicleCode}</strong><small>{isDelivery?'一号搅拌站 → 南城工地':state.short+'厂家 → '+state.warehouse}</small></div>
          {surface==='3d'&&objectCardOpen&&<SceneObjectCard selectedId={selectedId} detail={detail} workflow={state} onClose={()=>setObjectCardOpen(false)} onFocus={focusObject} onAction={handleAction}/>}
          {surface==='3d'&&<div className="scene-bottom-tools"><span>拖动旋转 · 滚轮缩放 · 点击对象</span><small className="v6-camera-mode">{autoCamera?'镜头随流程':'手动浏览'}</small><button aria-pressed={autoCamera} className={autoCamera?'active':''} onClick={autoCamera?manualControl:resumeFollow}>{autoCamera?'跟随流程':'恢复流程跟随'}</button><button aria-pressed={cutaway} onClick={()=>{setCutaway(!cutaway);setAutoCamera(false);}}>剖视</button></div>}
          {!ready&&<div className="loading-overlay">正在准备场景…</div>}
        </div>
        <div className="task-ribbon"><div className="task-now"><span className="phase-index">{String(state.stageIndex+1).padStart(2,'0')}</span><div><strong>{state.phase.label}</strong><small>{state.vehicleCode} · {isDelivery?'车载 '+fmt(state.onboardVolume)+' m³':'本车入库 '+fmt(state.stockAdded)+' t'}</small></div></div><div className="ribbon-actions"><button className={'play-button '+(blocked?'fault':'')} onClick={togglePlay}><Icon name={blocked?'alert':paused||state.completed?'play':'pause'} size={15}/>{mainAction}</button><button className="icon-button" aria-label="从头演示" onClick={restart}><Icon name="reset" size={17}/></button><select value={speed} aria-label="演示速度" onChange={e=>setSpeed(Number(e.target.value))}>{[1,2,4].map(n=><option key={n} value={n}>{n}×</option>)}</select></div></div>
        <div className="task-progress"><span>{clock(state.time)}</span><input aria-label="流程演示时间" type="range" min="0" max={state.total} step=".1" value={state.time} onChange={e=>seek(e.target.value)}/><span>{clock(state.total)}</span><button className="text-button" aria-expanded={detailsOpen} onClick={()=>setDetailsOpen(!detailsOpen)}>{detailsOpen?'收起步骤':'全部步骤'}</button></div>
        <ProcessFlow workflow={state} paused={paused||blocked} blocked={blocked} onFocus={focusObject}/>
        <div className="phase-strip">{groups.map(([label,start,end,preview])=><button key={label} className={state.stageIndex>end?'passed':state.stageIndex>=start?'current':''} onClick={()=>jumpStage(state.stages[preview])}><i>{state.stageIndex>end?<Icon name="check" size={12}/>:null}</i>{label}</button>)}</div>
        {detailsOpen&&<div className="phase-details"><p>{state.phase.description}</p><div className="v5-stage-preview"><span>点击步骤预览关键动作</span><button onClick={()=>jumpStage(state.phase,true)}><Icon name="play" size={13}/>从本步骤播放</button></div><div>{state.stages.map(stage=><button key={stage.key} className={state.stageIndex===stage.index?'active':''} onClick={()=>jumpStage(stage)}>{String(stage.index+1).padStart(2,'0')} {stage.label}</button>)}</div></div>}
      </section>
      <details className="business-panel" open>
      <summary><strong>对象与业务操作</strong><span>{detail.title}</span><small>展开 / 收起</small></summary>
      <aside className="context-panel" aria-label="对象与业务操作">
        <section className="object-context"><div className="context-eyebrow"><span>{detail.type}</span><button className="icon-button" aria-label={'定位'+detail.title} onClick={()=>focusObject(selectedId)} disabled={selectedId.startsWith('snapshot-')}><Icon name="focus" size={17}/></button></div><div className="object-title"><h2>{detail.title}</h2><span className={'status-pill '+(selectedId==='conveyor-b01'&&faultActive?'red':detail.source==='snapshot'?'muted':'')}>{detail.status}</span></div><dl className="object-fields">{detailFields.slice(0,4).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
          {recipeVisible?<div className="recipe-operation"><div className="recipe-status"><span className={state.trialPassed?'done':''}>1 试配</span><span className={state.recipeApproved?'done':''}>2 确认</span><span className={state.productionProgress>0?'done':''}>3 生产</span></div><div className="recipe-actions"><button disabled={state.recipeApproved} onClick={()=>controlAction('trial')}>试配预演</button><button disabled={!state.trialPassed||state.recipeApproved} onClick={()=>controlAction('approve')}>确认配方</button></div><button className="primary-button" disabled={!state.recipeApproved||faultActive||state.productionProgress>=1} onClick={()=>controlAction('production')}>{faultActive?'故障待处理':state.productionProgress>=1?'本批生产完成':'启动自动生产'}</button></div>:<button className="object-action" onClick={()=>handleAction(detail.nextAction)}>{detail.nextAction?.label||'查看关联任务'}<Icon name="arrow" size={16}/></button>}
          {selectedId==='cement-c02'&&<div className="replenishment-form">{replenishment?<><strong>{replenishment.task}</strong><span>已安排 {replenishment.quantity} t · 待到货复磅</span></>:<><label>补料数量<input aria-label="C02补料数量" type="number" min="1" max="50" step=".1" value={replenishmentQty} onChange={e=>setReplenishmentQty(e.target.value)}/><span>t</span></label><button onClick={planReplenishment}>创建演示补料单</button></>}<small>本地演示记录</small></div>}
          <small className="data-origin">{detail.source==='snapshot'?'示例快照': '当前流程联动'}</small>
        </section>
        {workspace==='materials'&&<section className="inventory-panel"><div className="panel-heading"><h3>原料库存</h3><span>t</span></div><div className="material-tabs">{Object.entries({sand:'砂',stone:'碎石',cement:'水泥',flyash:'粉煤灰'}).map(([id,label])=><button key={id} className={scenarioId===id?'active':''} onClick={()=>chooseScenario(id)}>{label}</button>)}</div>{operations.stocks.map(stock=><button key={stock.id} className={'stock-row '+(selectedId===stock.entityId?'selected':'')} onClick={()=>focusObject(stock.entityId)}><span><strong>{stock.name}</strong><small>{stock.source==='workflow'?'本车联动':'基准快照'}</small></span><div><b>{fmt(stock.current)}</b><div className="stock-track"><i style={{width:stock.ratio*100+'%'}}/></div></div><small>{Math.round(stock.ratio*100)}%</small></button>)}<div className="receipt-note">{state.receipted?<><Icon name="check" size={14}/>已复磅入库 +{fmt(state.stockAdded)} t</>:<><Icon name="truck" size={14}/>卸料后须复磅，当前未增加库存</>}</div><div className="inline-links"><button onClick={()=>focusObject('weighbridge-w01')}>查看称重</button><button onClick={()=>focusObject(state.flowKind==='aggregate'?'loader-l01':state.targetId)}>{state.flowKind==='aggregate'?'装载机供料':'粉料卸料口'}</button></div></section>}
        {workspace==='alerts'?<section className="alerts-panel"><div className="panel-heading"><h3>异常处置</h3><span>{operations.alerts.length} 项</span></div>{operations.alerts.map(alert=><div className={'alert-row '+alert.tone} key={alert.id}><div><Icon name="alert" size={16}/><strong>{alert.title.replace(' · 模拟','').replace(' · 示例快照','')}</strong></div><p>{alert.description}</p><div className="alert-actions"><span>{alert.status}</span><button onClick={()=>handleAction(alert.action)}>{alert.action.label}</button></div>{alert.nextAction&&<button className="clear-fault" onClick={()=>handleAction(alert.nextAction)}>{alert.nextAction.label}</button>}</div>)}<button className="simulate-fault" onClick={()=>{setFaultActive(!faultActive);setAcknowledged(false);setSelectedId('conveyor-b01');notify(faultActive?'演示故障已清除。':'B01 演示故障已触发，骨料供料与生产将阻断。');}}>{faultActive?'结束故障演示':'演示 B01 输送带故障'}</button></section>:<section className="fleet-panel"><div className="panel-heading"><h3>{workspace==='materials'?'收货与运输':'运输任务'}</h3><span>3 辆</span></div>{operations.fleet.map((row,i)=><button key={row.id} className={'fleet-row '+(selectedId===row.entityId?'selected':'')} onClick={()=>row.source==='workflow'?focusObject(row.entityId):handleAction(row.action)}><span className="fleet-symbol"><Icon name="truck"/></span><span className="fleet-main"><strong>{row.vehicleCode}<small>{i===0?'流程联动':'快照'}</small></strong><span>{row.target.replace(' · 示例','')}</span><small>{row.status.replace(' · 示例快照','')}</small></span><span className="fleet-quantity">{row.quantity!=null?fmt(row.quantity):'待核算'}<small>{row.unit}</small></span></button>)}<button className="transport-link" onClick={()=>{setSelectedId(state.vehicleId);setSurface('map');setAutoCamera(false);}}>查看当前车辆路线<Icon name="arrow" size={15}/></button></section>}
        {workspace==='delivery'&&<div className="delivery-summary"><span>本趟交付</span><strong>{fmt(state.deliveredVolume)} / {state.plannedVolume} <small>m³</small></strong><p>{state.delivered?'工地已签收，返站保留交付记录':'到达与签收分别记录；签收前交付量为 0'}</p><button onClick={()=>focusObject('construction-site')}>查看工地泵送</button></div>}
        {workspace==='production'&&<div className="process-links"><span>一体生产线</span><div>{[['automatic-bins','骨料下料'],['conveyor-b01','皮带输送'],['cement-c01','粉料计量'],['mixer-m01','搅拌主楼']].map(([id,label])=><button key={id} onClick={()=>focusObject(id)}>{label}</button>)}</div></div>}
      </aside>
      </details>
    </main>
    <footer className="ops-footer"><span>全站基准为演示快照 · 当前任务按流程联动</span><span>{state.task}<i/>V6</span></footer>
    {settingsOpen&&<div className="settings-popover"><div className="panel-heading"><h3>演示设置</h3><button className="text-button" onClick={()=>setSettingsOpen(false)}>关闭</button></div><label><input type="checkbox" checked={showRoutes} onChange={e=>setShowRoutes(e.target.checked)}/>显示任务路线</label><label><input type="checkbox" checked={autoCamera} onChange={e=>{if(e.target.checked)resumeFollow();else manualControl();}}/>镜头跟随流程</label><label>画面质量<select className="v6-quality-select" aria-label="画面质量" value={quality} onChange={e=>{setRenderStats(null);setQuality(e.target.value);}}>{Object.entries(QUALITY_LABELS).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>{qualityState&&<small className="v6-quality-status">当前：{QUALITY_LABELS[qualityState.effective]||qualityState.effective} · 像素比 {Number(qualityState.dpr).toFixed(2)} · 阴影 {qualityState.shadows?qualityState.shadowMapSize:'关闭'}</small>}<label>当前演示任务<select aria-label="选择演示任务" value={scenarioId} onChange={e=>{chooseScenario(e.target.value);setWorkspace(e.target.value==='delivery'?'production':'materials');}}>{Object.entries(SCENARIOS).map(([id,scenario])=><option value={id} key={id}>{scenario.label}</option>)}</select></label><button disabled={!ready||exporting} onClick={exportModel}>{exporting?'正在导出…':'导出当前 3D 场景'}</button><label><input type="checkbox" checked={sampling} onChange={e=>{setRenderStats(null);setSampling(e.target.checked);}}/>性能采样</label>{sampling&&renderStats&&<div className="v5-performance" role="status"><strong>{renderStats.fps} FPS · 帧间隔 P95 {renderStats.p95} ms</strong><span>{renderStats.samples} 帧采样 · 平均绘制 {renderStats.meanCalls??renderStats.calls} 次</span><span>几何缓存 {renderStats.geometries} · 纹理 {renderStats.textures} · 超过100ms {renderStats.longFrames??0} 帧</span><small>{surface==='map'?'路线模式：三维渲染已停止':paused?'暂停采样：静态绘制':'播放采样：包含镜头和动画'}</small></div>}<p>流程时间经过压缩；模型可操作，数据尚未接入现场设备。</p></div>}
    {modelFile&&settingsOpen&&<div className="model-download"><a href={modelFile.url} download="ready-mix-plant-v6.glb">下载 GLB · {Math.round(modelFile.bytes/1024)} KB</a></div>}
    {message&&<div className="toast" role="status">{message}</div>}
  </div>;
}

